### ISSUE TITLE
Option to allow coloring of user popouts even if an activity is present

### ISSUE THREAD

**Issue by sitiom** [powercord-community/rolecolor-everywhere#19]
For themes like [amazing-activity-cards](https://github.com/Discord-Theme-Addons/amazing-activity-cards).
![example](https://user-images.githubusercontent.com/56180050/113525131-c4fe9480-95e5-11eb-9031-864470fc18e3.png)

**Comment by cyyynthia** [comment]
The role color is exposed to themes as a variable, so I suggest you to ask theme developers instead, for a better per-theme integration (themes knows better than the plugin how things are meant to be) 
![image](https://user-images.githubusercontent.com/9999055/113691028-55afa000-96cc-11eb-8652-6b38e51e79eb.png)

**Comment by sitiom** [comment]
Thanks, this snippet fixes it for [amazing-activity-cards](https://github.com/Discord-Theme-Addons/amazing-activity-cards). This has to go to the theme now.
```css
/*  Role Color Everywhere */
.rolecolor-colored-userpopout {
    color: var(--color) !important;
}

.rolecolor-colored-userpopout .headerTagUsernameNoNickname-2_H881 {
    color: inherit;
}

.rolecolor-colored-userpopout span:not([class]) {
    opacity: 0.6;
}
```

Thanks for your help.
